name: build and publish docker image with demo app


on: [workflow_dispatch]

env:
  DOCKERHUB_NAMESPACE: jcdb
  DOCKERHUB_IMAGE_NAME: jcdb-demo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'liberica'
          java-package: jdk+fx

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.8
      - name: Build with Gradle
        run: gradle clean bootJar

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          push: true
          # read more about contexts at:
          #   https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
          tags: ${{ env.DOCKERHUB_NAMESPACE }}/${{ env.DOCKERHUB_IMAGE_NAME }}:${{ github.sha }}
          context: .
          file: jcdb-http/Dockerfile
